server:
  port: ${PORT:8080}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_urm?allowPublicKeyRetrieval=true
    username: root
    password: xBrecumax25%
    driver-class-name: com.mysql.cj.jdbc.Driver
jwt:
  secret: your_secret_key
  expirationMs: 86400000